### ISSUE TITLE
StackOverflowError in peekIgnoringErrors

### ISSUE THREAD

**Issue by stromnet** [vermut/intellij-snakeyaml#12]
Opening a RAML file (yaml format), I got this:

```null
java.lang.StackOverflowError
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:33)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
.....
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
```

No idea where to even start looking so...

**Comment by stromnet** [comment]
Seems to occur as soon as I try to edit the file. Jconsole thread dump while waiting after entering some random words in the doc:

```
Name: Document commit thread
State: RUNNABLE
Total blocked: 475  Total waited: 766

Stack trace: 
java.lang.Throwable.fillInStackTrace(Native Method)
java.lang.Throwable.fillInStackTrace(Throwable.java:783)
   - locked org.yaml.snakeyaml.scanner.ScannerException@4e0a0528
java.lang.Throwable.<init>(Throwable.java:287)
java.lang.Exception.<init>(Exception.java:84)
java.lang.RuntimeException.<init>(RuntimeException.java:80)
org.yaml.snakeyaml.error.YAMLException.<init>(YAMLException.java:30)
org.yaml.snakeyaml.error.MarkedYAMLException.<init>(MarkedYAMLException.java:34)
org.yaml.snakeyaml.error.MarkedYAMLException.<init>(MarkedYAMLException.java:29)
org.yaml.snakeyaml.scanner.ScannerException.<init>(ScannerException.java:47)
org.yaml.snakeyaml.scanner.ScannerException.<init>(ScannerException.java:64)
org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:248)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:33)
.....
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:50)
lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekToken(ErrorSkippingScanner.java:69)
lv.kid.vermut.intellij.yaml.lexer.YamlLexer.advance(YamlLexer.java:78)
com.intellij.lang.impl.PsiBuilderImpl.cacheLexemes(PsiBuilderImpl.java:284)
com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:192)
com.intellij.lang.impl.PsiBuilderImpl.<init>(PsiBuilderImpl.java:200)
com.intellij.lang.impl.PsiBuilderFactoryImpl.createBuilder(PsiBuilderFactoryImpl.java:52)
com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:83)
com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:172)
com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
com.intellij.psi.impl.source.text.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:327)
com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:273)
com.intellij.psi.impl.source.text.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:212)
com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:90)
com.intellij.psi.impl.DocumentCommitProcessor.doCommit(DocumentCommitProcessor.java:133)
com.intellij.psi.impl.DocumentCommitThread$4.run(DocumentCommitThread.java:471)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:483)
com.intellij.psi.impl.DocumentCommitThread.access$400(DocumentCommitThread.java:50)
com.intellij.psi.impl.DocumentCommitThread$3.run(DocumentCommitThread.java:357)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:354)
com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:298)
java.lang.Thread.run(Thread.java:745)
```

**Comment by vermut** [comment]
omg. can you attach actual file?

**Comment by stromnet** [comment]
Sorry, internal file so cannot share that. But it's quite large, 1146 lines. Atom handles it fine btw.
If you have any hints on what to look at I might be able to create an isolated example.

**Comment by vermut** [comment]
Look for unusual constructions. Template markup, special symbols.
Try pasting the code to http://yaml-online-parser.appspot.com/ and see where (if) it fails.

**Comment by vermut** [comment]
Or maybe custom tags? Like 
exampleCollection: !include jukebox-include-artist-albums.sample

**Comment by stromnet** [comment]
Yes, the !include tag is used to include JSON files (schemas and examples in the raml output)

On February 17, 2016 12:18:55 PM GMT+01:00, Pavel Veretennikov <notifications@github.com> wrote:
>Or maybe custom tags? Like 
>exampleCollection: !include jukebox-include-artist-albums.sample 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vermut/intellij-snakeyaml/issues/12#issuecomment-185159181

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
I'm getting a similar error when editing a large (17264 lines) YAML file. It doesn't include any custom tags and we're using SnakeYAML to parse it in our project, so I know that works.

It's an internal file so I can't upload it here. I tried the online parser but it doesn't seem to be able to deal with large files, I just get:
```
Output
An error occured. Try again? Or contact me.
```

Here's the backtrace:

```
No message
java.lang.StackOverflowError
	at org.yaml.snakeyaml.error.Mark.get_snippet(Mark.java:88)
	at org.yaml.snakeyaml.error.Mark.toString(Mark.java:93)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.yaml.snakeyaml.error.MarkedYAMLException.<init>(MarkedYAMLException.java:34)
	at org.yaml.snakeyaml.error.MarkedYAMLException.<init>(MarkedYAMLException.java:29)
	at org.yaml.snakeyaml.scanner.ScannerException.<init>(ScannerException.java:47)
	at org.yaml.snakeyaml.scanner.ScannerException.<init>(ScannerException.java:64)
	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:248)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:35)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:53)
	at 
... [many repeats of the same line] ...
```

**Comment by ghost** [comment]
I enabled the extra debug logging and got this (while adding a key to an existing mapping in the file):
```
2017-03-17 09:05:28,485 [1560524]  DEBUG - aml.lexer.ErrorSkippingScanner -  
while scanning a simple key
 in 'reader', line 5373, column 5:
        r
        ^
could not find expected ':'
 in 'reader', line 9290, column 13:
    mdlinx.com: {diffbot: 1, location: us}
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:248)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:35)
	at lv.kid.vermut.intellij.yaml.lexer.ErrorSkippingScanner.peekIgnoringErrors(ErrorSkippingScanner.java:53)
...
```
